### ISSUE TITLE
Rainfall Almanac - Report rain total by rain year rather than calendar year 

### ISSUE THREAD

**Issue by steepleian** [lightmaster/Meteobridge-Weather34-Template#33]
In certain geographies it is custom to use a 'rain year' in records rather than a calendar year. For example I understand that the Californian rain year is from October to the following September. Is it then possible to amend the rainfall almanac to report the '**rain year**' total rather than current calendar ear?

I am not familiar enough with Meteobridge to understand how easy it is to generate data for a 'non-calendar' 12 months. For the Californian example above, in WeeWX, I would simply set the 'rain_year_start = 10' and then use the tag '$rainyear.rain.sum' (instead of $year.rain.sum) to extract the data from the database.

**Comment by lightmaster** [comment]
The rain year data is just copied from what the Meteobridge says is the rainfall for the year. I would think it'd be better for the Meteobridge to provide a custom "year" starting date and then we'd just continue to echo the numbers that Meteobridge sends out.

**Comment by lightmaster** [comment]
Looks like MB already has this feature. On Systems tab you can specify when your rain year begins, and then when your site asks MB how much rain has fallen in the "current year", it would get the amount of rain since the month that you choose.

[![Screenshot-20190515-061347-Chrome-Beta.jpg](https://i.postimg.cc/kXmMWz5J/Screenshot-20190515-061347-Chrome-Beta.jpg)](https://postimg.cc/7bKykB7d)
