### ISSUE TITLE
Rain Fall Almanac

### ISSUE THREAD

**Issue by steepleian** [lightmaster/Meteobridge-Weather34-Template#42]
![Screen Shot 2019-05-23 at 23 16 42](https://user-images.githubusercontent.com/18438654/58290275-18c8b180-7db1-11e9-8e21-456983d2ef50.png)

Slight adjustment to CSS required. At 100% zoom, the converted figures appear to merge into the blue blocks. More pronounced with Firefox and Chrome. Less pronounced with Safari (but gets worse when zoom factor is increased.

![Screen Shot 2019-05-23 at 23 22 00](https://user-images.githubusercontent.com/18438654/58290491-d358b400-7db1-11e9-9370-29ad98e87a7c.png)

**Comment by gand07** [comment]
No problem with Vivaldi.

gand

<img width="869" alt="2019-05-24 (2)" src="https://user-images.githubusercontent.com/47734099/58303756-c6f44b80-7df1-11e9-868c-4d52ebb18f06.png">

**Comment by weather34** [comment]
ok i will look at it this morning ,  i got boris to update the api yesterday so there will be additional data in the rain almanac also support for air quality where supported by meteobridge with some newer hardware by ecowitt(perhaps chuck should talk to boris about purple air and see if it is possible ?),also battery alert if console or ISS on davis hardware is low 
.the rainfall since for all time needs a new option in the easyweathersetup a simple a rainfall records started . 

171 [thb0lowbat-act:--] *may 2019 davis console battery
172 [th0lowbat-act:--] *may 2019 davis battery
173 [rain0total-max@M1] *may 2019 rainfall previous month
174 [rain0total-max@Y1] *may 2019 rainfall previous year
175 [air0pm-act:--] *may 2019 air quality

**Comment by lightmaster** [comment]
> ![Screen Shot 2019-05-23 at 23 16 42](https://user-images.githubusercontent.com/18438654/58290275-18c8b180-7db1-11e9-8e21-456983d2ef50.png)
> 
> Slight adjustment to CSS required. At 100% zoom, the converted figures appear to merge into the blue blocks. More pronounced with Firefox and Chrome. Less pronounced with Safari (but gets worse when zoom factor is increased.
> 
> ![Screen Shot 2019-05-23 at 23 22 00](https://user-images.githubusercontent.com/18438654/58290491-d358b400-7db1-11e9-9370-29ad98e87a7c.png)

Check my site's almanacs, made some slight adjustments to the top boxes for temp, wind, and rain, particularly the gray bar that houses the converted units. Should fix your issue @steepleian

**Comment by steepleian** [comment]
Thanks William. Will check out this evening.

**Comment by steepleian** [comment]
Just managed to get a quick look on my iPad and it does look better. 
Thanks

**Comment by lightmaster** [comment]
> Just managed to get a quick look on my iPad and it does look better. Thanks

So looks good on all your browsers?

**Comment by steepleian** [comment]
Still not so good with Sierra MacOS, all others OK including Sierra iOS

**Comment by lightmaster** [comment]
Is it just the rain almanac that's not right, or all the almanacs?

**Comment by steepleian** [comment]
The others look ok

**Comment by hansmestrum** [comment]
Hi,

The others are one now. But the rain graphs do not update.


Op 31 mei 2019 bij 10:18:48, Ian Millard (notifications@github.com) schreef:

The others look ok

Sent from my iPhone

> On 30 May 2019, at 00:04, lightmaster <notifications@github.com> wrote:
>
> Is it just the rain almanac that's not right, or all the almanacs?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lightmaster/Meteobridge-Weather34-Template/issues/42?email_source=notifications&email_token=ABIOVYMQRIAHGOPS2CP5HBLPYDNORA5CNFSM4HPKYFQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWURTWI#issuecomment-497621465>,
or mute the thread

**Comment by lightmaster** [comment]
changed the CSS on my rain almanac again, look better, worse, or the same?

**Comment by steepleian** [comment]
Looking good on my browsers at 100% and higher zoom values.

**Comment by lightmaster** [comment]
before I push, all the gray bars of converted measurements on all the almanacs look good, right?

**Comment by steepleian** [comment]
Yes they are good.

**Comment by hansmestrum** [comment]
Hi

As you can see on http://mooiweerboxtel.nl/pws/ current situation is not right. It says Overcast conditions, but the weather is sunny, hardly any clouds.

Sent from Mail for Windows 10

**Comment by lightmaster** [comment]
> Hi As you can see on http://mooiweerboxtel.nl/pws/ current situation is not right. It says Overcast conditions, but the weather is sunny, hardly any clouds. Sent from Mail for Windows 10

Please create your own Issue if there isn't already one related to the problem you've found.

That being said, we don't actually generate the forecast, we just pull the forecast from your METAR station and from WU/DsrkSky. Right now your Metar station said it was Overcast, and now Scattered Clouds.
