### ISSUE TITLE
Slow Database Update

### ISSUE THREAD

**Issue by chrismaltese** [lightmaster/Meteobridge-Weather34-Template#48]
Not sure if this is a bug or change in design, but I notice that my database updates every 5 minutes instead of every 10 secs that I used to see.  One of the things that I see is that wind gust updates every 5 minutes as a result.

Any guidance?

--Thanks / Chris

![Greenshot 2019-06-11 16 54 28](https://user-images.githubusercontent.com/47764765/59306222-d4bb2500-8c69-11e9-8903-a1d1ed1120eb.png)
![Greenshot 2019-06-11 16 55 29](https://user-images.githubusercontent.com/47764765/59306231-d84eac00-8c69-11e9-95bd-2a5416bd742b.png)

**Comment by lightmaster** [comment]
This is a feature, not a bug, and is working as designed. Your modules will update in realtime, but the database (used only for charts) are updated with 5 minute averages which helps the today graphs display nicer (used to show 6000+ plots on graph) and makes the today graphs nicer and smoother. Almanacs are updated live via tags from your MB, so they aren't effected by this either.

Gusts on the module are updated live, but they are defined as the max wind speed within the last 10 minutes. Previously, the gusts had actually been the current wind speed instead of max wind speed.

**Comment by chrismaltese** [comment]
Fair enough and good explanation. Much appreciated.
