### ISSUE TITLE
no update for forcast wu, ds, .......

### ISSUE THREAD

**Issue by palafran** [lightmaster/Meteobridge-Weather34-Template#50]
Hi,
I use this Weather Template since 2 Years
today I made the first update this Year, 18.6.19
the problem I see, no update for airquality, earthquake, nearby metar, forcast wu, ds, current conditions.
I see that the Folder of Jonsdata are empty

**Comment by lightmaster** [comment]
What's your url so I can take a look?

If it's the first time you've updated since I've taken over, there was an update a while back that required you to do a full reinstall. Rename your sites folder to include .bak after it, then create a new folder and install the current version of the template into it. Then copy your settings1.php, mbcharts yearly and monthly .CSV files, mbcharts/result.csv, and jsondata/ from the .bak copy to your fresh copy so all the data will be preserved. Also, if you haven't in a while, make sure to reboot your MB since there have been several updates to the API to include more data in the site.

If you used WU to generate your charts instead of mbcharts, unfortunately with all the trouble that WU has been lately, @weather34 and I have decided to drop WU support for charts. They are still an option for limited forecasts, however their on-again off-again attitude towards letting you access your own data is too much trouble, considering there's a much better option that doesn't rely on any other service, only your own server.

**Comment by palafran** [comment]
Hello,
thank you for your help
I am sorry that I am only now reporting
I still have a second problem
my MB is broken and I first fix this problem
